sudo: false
language: java
jdk:
  - oraclejdk8
  - oraclejdk9
addons:
  apt:
    packages:
      - oracle-java8-installer
script:
  - javac src/com/ltse/gui/Main.java
  - javac ltse-tool/ltse/LTSExtractor.java